name: build and push docker images to dockerhub

on:
  push:
    branches:
      - main

jobs:
  DKRBUILD:
    runs-on: ubuntu-latest
    steps:
        - name: checkout the repository
          uses: actions/checkout@v2

        - name: setup docker builtx
          uses: docker/setup-buildx-action@v1
        
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUBUSER }}
            password: ${{ secrets.DOCKERPASS }}
          

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./DockerFiles
            platforms: linux/amd64,linux/arm64
            push: true
            tags: nileshdalagade/mlflow_git_model:latest
            build-args: |
              RUNID=e8fc65334bf049b8ad0b9d0f243b1ed5

