name: build and push docker images to dockerhub

on:
  push:
    branches:
      - main

jobs:
  DKRBUILD:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
    steps:
        - name: checkout the repository
          uses: actions/checkout@v2

        - name: setup docker builtx
          uses: docker/setup-buildx-action@v1
        
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUBUSER }}
            password: ${{ secrets.DOCKERPASS }}
          

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64
            push: true
            tags: nileshdalagade/mlflow_git_model:latest
            build-args: |
              RUNID=e8fc65334bf049b8ad0b9d0f243b1ed5
              MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
              MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
              MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}

