name: programming run

on:
    push:
        branches:
            - main

jobs:
    Generator:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            
            - name: set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: create environment
              run: |
                python -m venv myenv
                source myenv/bin/activate

            - name: install dependencies
              run: |
                pip install -r requirements.txt

            - name: store env
              uses: actions/upload-artifact@v2
              with:
                name: virtual-env
                path: myenv


            - name: Run the script and generate artifact
              run: |
                python script.py
                
            - name: store generated artifact
              uses: actions/upload-artifact@v2
              with:
                name: generated-files
                path: ./files
    
    Consumer:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: download-artifacts
              uses: actions/download-artifact@v2
              with:
                name: virtual-env
                path: myenv

            - name: activate env
              run: |
                source myenv/bin/activate

            - name: download generated artifact
              uses: actions/download-artifact@v2
              with:
                name: generated-files
                path: ./files
            
            - name: run the display.py file
              run: |
                python display.py

    
                

            