name: programming run

on:
    push:
        branches:
            - main

jobs:
    calculates:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            
            - name: set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: create environment
              run: |
                python -m venv myenv
                source myenv/bin/activate

            - name: install dependencies
              run: |
                pip install -r requirements.txt

            - name: Run the script and set env
              run: |
                MYENV = $(python script.py)
                echo "MYENV=$MYENV" >> $GITHUB_ENV
                

            - name: Lets print
              run: |
                echo "my answer is : MYENV"

            