name: programming run

on:
    push:
        branches:
            - main

jobs:
    Generator:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            
            - name: set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: create environment
              run: |
                python -m venv myenv
                source myenv/bin/activate

            - name: install dependencies
              run: |
                pip install -r requirements.txt

            - name: Cache virtual environment
              uses: actions/cache@v3
              with:
                path: |
                    myenv
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
              if: success()


            - name: Run the script and generate artifact
              run: |
                python script.py
                
            - name: store generated artifact
              uses: actions/upload-artifact@v3
              with:
                name: generated artifact
                path: new.py
    
    Consumer:
        runs-on: ubuntu-latest
        needs: Generator
        steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: Restore virtual environment
              uses: actions/cache@v3
              with:
                path: |
                    myenv
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

            - name: activate env
              run: |
                source myenv/bin/activate

            - name: download generated artifact
              uses: actions/download-artifact@v3
              with:
                name: generated artifact
            
            - name: run the display.py file
              run: |
                python display.py

    
                

            